### PR TITLE
Update dependencies on setup.py update.

### PR DESCRIPTION
**Pull request by Natim**
See: https://github.com/mozilla-services/kinto/pull/126#issuecomment-119617258

### CODE REVIEW

**Comment by n1k0** [comment]
I don't have a clue how to review this accurately. Maybe @leplatrem or @ametaireau are better fits here?

**Comment by Natim** [comment]
To review accurately:
 - Drop your venv
 - Checkout the last tag and run ``make serve``
 - Checkout master
 - try to run ``make serve``

**Comment by Natim** [comment]
We did it for cliquet https://github.com/mozilla-services/cliquet/blob/master/Makefile#L17 but we didn't for Kinto yet.

**Comment by n1k0** [comment]
Still fails for me:

- on the 1.2.1 tag: https://pastebin.mozilla.org/8838963
- on the patch branch: https://pastebin.mozilla.org/8838971

**Comment by Natim** [comment]
Updated.

**Comment by n1k0** [comment]
That fixed it! r+

**Pull request merged**
