### PR TITLE
Add pytest-cache

### PR DESCRIPTION
**Pull request by Natim**
r? @magopian

### CODE REVIEW

**Comment by magopian** [comment]
yep, that allows using the `--lf` (for "last failed") to the test run command, which will only re-run the tests that failed. It's awesome, you should use it ;)

Also, if you want to give it a try:
- `pip install pytest-xdist`
- `py.test --cov-report term-missing --cov-fail-under 100 --cov kinto -n 4 --nosugar`

pytest-xdist is not compatible with pytest-sugar I believe, hence the `--nosugar`.

This will run the tests in parallel on 4 workers/cores, which should be much faster ;)

**Comment by Natim** [comment]
Yes it is much faster.

**Comment by Natim** [comment]
PR Updated.

**Comment by Natim** [comment]
I don't think pytest-xdist is a good idea here since test are instable with it and not that much faster :)

**Comment by magopian** [comment]
I agree. `pytest-cache` would still be good though

**Comment by Natim** [comment]
Yes see https://github.com/mozilla-services/kinto/pull/98

**Pull request closed without merging**
